name: Python Tests

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }} # Установка двух необходимых runner-ов
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python # Установка версии Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 

    - name: Install dependencies # Установка всех необходимых библиотек из requirements.txt 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run tests
      run: pytest test.py
